let n = 20;

export let solarSystem = {
  verticalKaificent: 0,
  mercury: {
    delta: 0,
    x: 0,
    y: 0,
    r: 90,
    rotationSpeed: 47.87,
    orbitalSpeed: 360 / (88 * n),
    box: document.querySelector(".galaxy__container__mercury"),
    shadow: document.querySelector(".galaxy__shadow__mercury"),
    circle: document.querySelector(".galaxy__circles__mercury"),
  },
  venus: {
    delta: 0,
    x: 0,
    y: 0,
    r: 140,
    rotationSpeed: 35.02,
    orbitalSpeed: 360 / (224.7 * n),
    box: document.querySelector(".galaxy__container__venus"),
    shadow: document.querySelector(".galaxy__shadow__venus"),
    circle: document.querySelector(".galaxy__circles__venus"),
  },
  earth: {
    delta: 0,
    x: 0,
    y: 0,
    r: 185,
    rotationSpeed: 29.78,
    orbitalSpeed: 360 / (365.25 * n),
    box: document.querySelector(".galaxy__container__earth__moon"),
    shadow: document.querySelector(".galaxy__shadow__earth"),
    circle: document.querySelector(".galaxy__circles__earth"),
  },
  mars: {
    delta: 0,
    x: 0,
    y: 0,
    r: 240,
    rotationSpeed: 24.077,
    orbitalSpeed: 360 / (687 * n),
    box: document.querySelector(".galaxy__container__mars"),
    shadow: document.querySelector(".galaxy__shadow__mars"),
    circle: document.querySelector(".galaxy__circles__mars"),
  },
  jupiter: {
    delta: 0,
    x: 0,
    y: 0,
    r: 320,
    rotationSpeed: 13.07,
    orbitalSpeed: 360 / (4333 * n),
    box: document.querySelector(".galaxy__container__jupiter"),
    shadow: document.querySelector(".galaxy__shadow__jupiter"),
    circle: document.querySelector(".galaxy__circles__jupiter"),
  },
  saturn: {
    delta: 0,
    x: 0,
    y: 0,
    r: 430,
    rotationSpeed: 9.69,
    orbitalSpeed: 360 / (10759 * n),
    box: document.querySelector(".galaxy__container__saturn__ring"),
    shadow: document.querySelector(".galaxy__shadow__saturn"),
    circle: document.querySelector(".galaxy__circles__saturn"),
  },
  uranus: {
    delta: 0,
    x: 0,
    y: 0,
    r: 510,
    rotationSpeed: 6.81,
    orbitalSpeed: 360 / (30687 * n),
    box: document.querySelector(".galaxy__container__uranus"),
    shadow: document.querySelector(".galaxy__shadow__uranus"),
    circle: document.querySelector(".galaxy__circles__uranus"),
  },
  neptune: {
    delta: 0,
    x: 0,
    y: 0,
    r: 560,
    rotationSpeed: 5.43,
    orbitalSpeed: 360 / (60190 * n),
    box: document.querySelector(".galaxy__container__neptune"),
    shadow: document.querySelector(".galaxy__shadow__neptune"),
    circle: document.querySelector(".galaxy__circles__neptune"),
  },
};
